Document: amigu
Title: Debian amigu Manual
Author: <insert document author here>
Abstract: This manual describes what amigu is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amigu/amigu.sgml.gz

Format: postscript
Files: /usr/share/doc/amigu/amigu.ps.gz

Format: text
Files: /usr/share/doc/amigu/amigu.text.gz

Format: HTML
Index: /usr/share/doc/amigu/html/index.html
Files: /usr/share/doc/amigu/html/*.html
